In [2]:
# À exécuter dans votre terminal si ce n'est pas fait :
# pip install soccerdata pandas

import soccerdata as sd
import pandas as pd

# Afficher toutes les colonnes pour une meilleure visibilité
pd.set_option('display.max_columns', None)

In [3]:
# Initialisation du scraper FBref
# "FRA-Ligue 1" est l'identifiant standard pour le championnat de France
fbref = sd.FBref(leagues="FRA-Ligue 1", seasons="25-26")

print("API FBref initialisée pour la Ligue 1 (2025-2026)")

[05/11/26 14:17:24] INFO     Saving cached data to /Users/ethan.bcht/soccerdata/data/FBref           ]8;id=3429617;file:///Users/ethan.bcht/Dev/mlfoot/.venv/lib/python3.12/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=3429618;file:///Users/ethan.bcht/Dev/mlfoot/.venv/lib/python3.12/site-packages/soccerdata/_common.py#250\250]8;;\

Warning: uc_driver not found. Getting it now:

*** chromedriver to download = 147.0.7727.117 (Previous Version)

Downloading chromedriver-mac-x64.zip from:
https://storage.googleapis.com/chrome-for-testing-public/147.0.7727.117/mac-x64/chromedriver-mac-x64.zip ...
Download Complete!

Extracting ['chromedriver'] from chromedriver-mac-x64.zip ...
Unzip Complete!

The file [uc_driver] was saved to:
/Users/ethan.bcht/Dev/mlfoot/.venv/lib/python3.12/site-packages/seleniumbase/drivers/
uc_driver

Making [uc_driver 147.0.7727.117] executable ...
[uc_driver 147.0.7727.117] is now ready for use!


*** chromedriver to download = 147.0.7727.117 (Previous Version)

Downloading chromedriver-mac-arm64.zip from:
https://storage.googleapis.com/chrome-for-testing-public/147.0.7727.117/mac-arm64/chromedriver-mac-arm64.zip ...
Download Complete!

Extracting ['chromedriver'] from chromedriver-mac-arm64.zip ...
Unzip Complete!

The file [chromedriver] was saved to:
/Users/ethan.bcht/Dev/mlfoot/.venv/lib/python3.12/site-packages/seleniumbase/drivers/
chromedriver

Making [chromedriver 147.0.7727.117] executable ...
[chromedriver 147.0.7727.117] is now ready for use!

API FBref initialisée pour la Ligue 1 (2025-2026)

In [6]:
# Lecture des stats par équipe
team_stats = fbref.read_team_season_stats(stat_type="standard")

# On affiche les 5 premières lignes
team_stats

                                       players_used   Age  Poss Playing Time  \
                                                                          MP
league      season team
FRA-Ligue 1 2526   Angers                        30  26.7  41.9           33
                   Auxerre                       30  25.7  44.5           33
                   Brest                         26  27.4  42.9           32
                   Le Havre                      30  27.4  47.1           33
                   Lens                          29  27.3  51.8           32
                   Lille                         30  27.3  55.5           33
                   Lorient                       26  26.0  44.9           33
                   Lyon                          32  27.0  54.6           33
                   Marseille                     38  28.3  57.4           33
                   Metz                          33  27.0  48.8           33
                   Monaco                        32  26.5  53.6           33
                   Nantes                        33  26.9  42.1           33
                   Nice                          36  26.3  46.2           33
                   Paris FC                      31  28.1  50.8           33
                   Paris Saint-Germain           27  24.4  69.2           32
                   Rennes                        33  26.9  53.5           33
                   Strasbourg                    35  22.2  54.3           32
                   Toulouse                      26  24.9  42.3           33

                                                        Performance           \
                                       Starts   Min 90s         Gls Ast  G+A
league      season team
FRA-Ligue 1 2526   Angers                 363  2970  33          27  16   43
                   Auxerre                363  2970  33          28  18   46
                   Brest                  352  2880  32          40  28   68
                   Le Havre               363  2970  33          30  21   51
                   Lens                   352  2880  32          61  47  108
                   Lille                  363  2970  33          51  33   84
                   Lorient                363  2970  33          47  31   78
                   Lyon                   363  2970  33          52  41   93
                   Marseille              363  2970  33          59  45  104
                   Metz                   363  2970  33          31  20   51
                   Monaco                 363  2970  33          54  40   94
                   Nantes                 363  2970  33          28  18   46
                   Nice                   363  2970  33          35  25   60
                   Paris FC               363  2970  33          44  26   70
                   Paris Saint-Germain    352  2880  32          70  52  122
                   Rennes                 363  2970  33          56  41   97
                   Strasbourg             352  2880  32          50  35   85
                   Toulouse               363  2970  33          46  32   78

                                                               Per 90 Minutes  \
                                       G-PK PK PKatt CrdY CrdR            Gls
league      season team
FRA-Ligue 1 2526   Angers                24  3     5   50    2           0.82
                   Auxerre               25  3     5   67    7           0.85
                   Brest                 34  6     8   57    5           1.25
                   Le Havre              28  2     6   64    4           0.91
                   Lens                  57  4     5   62    5           1.91
                   Lille                 44  7     8   75    5           1.55
                   Lorient               44  3     6   53    1           1.42
                   Lyon                  49  3     5   60    7           1.58
                   Marseille             53  6     8   77    4           1.79
                   Metz                  26  5     6   54    4           0.94
                   Monaco                48  6     7   73    6           1.64
                   Nantes                26  2     4   67    2           0.85
                   Nice                  32  3     3   67    3           1.06
                   Paris FC              39  5     6   70    5           1.33
                   Paris Saint-Germain   65  5     8   35    2           2.19
                   Rennes                51  5     6   57    4            1.7
                   Strasbourg            44  6     7   58    5           1.56
                   Toulouse              42  4     7   78    5           1.39

                                                                 \
                                         Ast   G+A  G-PK G+A-PK
league      season team
FRA-Ligue 1 2526   Angers               0.48   1.3  0.73   1.21
                   Auxerre              0.55  1.39  0.76    1.3
                   Brest                0.87  2.12  1.06   1.94
                   Le Havre             0.64  1.55  0.85   1.48
                   Lens                 1.47  3.38  1.78   3.25
                   Lille                 1.0  2.55  1.33   2.33
                   Lorient              0.94  2.36  1.33   2.27
                   Lyon                 1.24  2.82  1.48   2.73
                   Marseille            1.36  3.15  1.61   2.97
                   Metz                 0.61  1.55  0.79   1.39
                   Monaco               1.21  2.85  1.45   2.67
                   Nantes               0.55  1.39  0.79   1.33
                   Nice                 0.76  1.82  0.97   1.73
                   Paris FC             0.79  2.12  1.18   1.97
                   Paris Saint-Germain  1.62  3.81  2.03   3.66
                   Rennes               1.24  2.94  1.55   2.79
                   Strasbourg           1.09  2.66  1.37   2.47
                   Toulouse             0.97  2.36  1.27   2.24

                                                                                  url

league      season team
FRA-Ligue 1 2526   Angers                            /en/squads/69236f98/Angers-Stats
                   Auxerre                          /en/squads/5ae09109/Auxerre-Stats
                   Brest                              /en/squads/fb08dbb3/Brest-Stats
                   Le Havre                        /en/squads/5c2737db/Le-Havre-Stats
                   Lens                                /en/squads/fd4e0f7d/Lens-Stats
                   Lille                              /en/squads/cb188c0c/Lille-Stats
                   Lorient                          /en/squads/d2c87802/Lorient-Stats
                   Lyon                                /en/squads/d53c0b06/Lyon-Stats
                   Marseille                      /en/squads/5725cc7b/Marseille-Stats
                   Metz                                /en/squads/f83960ae/Metz-Stats
                   Monaco                            /en/squads/fd6114db/Monaco-Stats
                   Nantes                            /en/squads/d7a486cd/Nantes-Stats
                   Nice                                /en/squads/132ebc33/Nice-Stats
                   Paris FC                        /en/squads/056a5a75/Paris-FC-Stats
                   Paris Saint-Germain  /en/squads/e2d8892c/Paris-Saint-Germain-Stats
                   Rennes                            /en/squads/b3072e00/Rennes-Stats
                   Strasbourg                    /en/squads/c0d3eab4/Strasbourg-Stats
                   Toulouse                        /en/squads/3f8c4b5f/Toulouse-Stats

In [7]:
# Récupération du calendrier complet
schedule = fbref.read_schedule()

# Affichage des 5 derniers matchs joués
schedule[schedule['score'].notna()].tail(5)

                                                         week  day       date  \
league      season game
FRA-Ligue 1 2526   2026-05-10 Metz-Lorient                 33  Sun 2026-05-10
                   2026-05-10 Monaco-Lille                 33  Sun 2026-05-10
                   2026-05-10 Paris Saint-Germain-Brest    33  Sun 2026-05-10
                   2026-05-10 Rennes-Paris FC              33  Sun 2026-05-10
                   2026-05-10 Toulouse-Lyon                33  Sun 2026-05-10

                                                          time  \
league      season game
FRA-Ligue 1 2526   2026-05-10 Metz-Lorient               21:00
                   2026-05-10 Monaco-Lille               21:00
                   2026-05-10 Paris Saint-Germain-Brest  21:00
                   2026-05-10 Rennes-Paris FC            21:00
                   2026-05-10 Toulouse-Lyon              21:00

                                                                   home_team  \
league      season game
FRA-Ligue 1 2526   2026-05-10 Metz-Lorient                              Metz
                   2026-05-10 Monaco-Lille                            Monaco
                   2026-05-10 Paris Saint-Germain-Brest  Paris Saint-Germain
                   2026-05-10 Rennes-Paris FC                         Rennes
                   2026-05-10 Toulouse-Lyon                         Toulouse

                                                        score away_team  \
league      season game
FRA-Ligue 1 2526   2026-05-10 Metz-Lorient                0–4   Lorient
                   2026-05-10 Monaco-Lille                0–1     Lille
                   2026-05-10 Paris Saint-Germain-Brest   1–0     Brest
                   2026-05-10 Rennes-Paris FC             2–1  Paris FC
                   2026-05-10 Toulouse-Lyon               2–1      Lyon

                                                         attendance  \
league      season game
FRA-Ligue 1 2526   2026-05-10 Metz-Lorient                     <NA>
                   2026-05-10 Monaco-Lille                     <NA>
                   2026-05-10 Paris Saint-Germain-Brest        <NA>
                   2026-05-10 Rennes-Paris FC                  <NA>
                   2026-05-10 Toulouse-Lyon                    <NA>

                                                                          venue  \
league      season game
FRA-Ligue 1 2526   2026-05-10 Metz-Lorient               Stade Saint-Symphorien
                   2026-05-10 Monaco-Lille                       Stade Louis II
                   2026-05-10 Paris Saint-Germain-Brest        Parc des Princes
                   2026-05-10 Rennes-Paris FC                      Roazhon Park
                   2026-05-10 Toulouse-Lyon                 Stadium de Toulouse

                                                                 referee  \
league      season game
FRA-Ligue 1 2526   2026-05-10 Metz-Lorient                 Jeremy Stinat
                   2026-05-10 Monaco-Lille                Clément Turpin
                   2026-05-10 Paris Saint-Germain-Brest   Jérôme Brisard
                   2026-05-10 Rennes-Paris FC             Thomas Léonard
                   2026-05-10 Toulouse-Lyon              Bastien Dechepy

                                                                                              match_report  \
league      season game
FRA-Ligue 1 2526   2026-05-10 Metz-Lorient               /en/matches/14a05a12/Metz-Lorient-May-10-2026-...
                   2026-05-10 Monaco-Lille               /en/matches/7694f275/Monaco-Lille-May-10-2026-...
                   2026-05-10 Paris Saint-Germain-Brest  /en/matches/06573726/Paris-Saint-Germain-Brest...
                   2026-05-10 Rennes-Paris FC            /en/matches/7741d788/Rennes-Paris-FC-May-10-20...
                   2026-05-10 Toulouse-Lyon              /en/matches/3133ca8e/Toulouse-Lyon-May-10-2026...

                                                         notes   game_id
league      season game
FRA-Ligue 1 2526   2026-05-10 Metz-Lorient                <NA>  14a05a12
                   2026-05-10 Monaco-Lille                <NA>  7694f275
                   2026-05-10 Paris Saint-Germain-Brest   <NA>  06573726
                   2026-05-10 Rennes-Paris FC             <NA>  7741d788
                   2026-05-10 Toulouse-Lyon               <NA>  3133ca8e